version: '2.0'
services:
  mock-server:
    container_name: mock_server
    build: .
    ports:
      - "5050:8080"
    volumes:
      - ./stubs/:/home/wiremock
  mock-server-https:
    container_name: mock_server_https
    build: .
    ports:
      - "6060:8443"
    volumes:
      - ./stubs/:/home/wiremock








